// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMz7CjJJ1TQmpYf6iRkrWUNxQF_KjuBy4',
    appId: '1:584094051085:android:07ada197b9d20b388a9e44',
    messagingSenderId: '584094051085',
    projectId: 'ordermap-fcf93',
    storageBucket: 'ordermap-fcf93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDiftCjvIgpUYvdeunvGKCqz23ROFyL-Y',
    appId: '1:973613420133:ios:50b724b69f7bb8dce4008c',
    messagingSenderId: '973613420133',
    projectId: 'random-c0851',
    storageBucket: 'random-c0851.firebasestorage.app',
    iosBundleId: 'com.example.ordermap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDiftCjvIgpUYvdeunvGKCqz23ROFyL-Y',
    appId: '1:973613420133:ios:50b724b69f7bb8dce4008c',
    messagingSenderId: '973613420133',
    projectId: 'random-c0851',
    storageBucket: 'random-c0851.firebasestorage.app',
    iosBundleId: 'com.example.ordermap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFOY5Bv473E3TkExjFz9hiadsqWa9RKEA',
    appId: '1:973613420133:web:8507ae35cdd84172e4008c',
    messagingSenderId: '973613420133',
    projectId: 'random-c0851',
    authDomain: 'random-c0851.firebaseapp.com',
    storageBucket: 'random-c0851.firebasestorage.app',
    measurementId: 'G-9NXWT9B0GX',
  );

}